According to Python, "NumPy is the fundamental package for scientific computing with Python."
It's used for working with arrays. NumPy arrays can be processed faster than Python lists.

In [18]:
# the conventional way to install numpy
import numpy as np
np.__version__

'1.26.4'

In [19]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

Arrays have dimensions. 0-D arrays are just numbers. They're called scalars. 1-D arrays have 0-D arrays as all their elements. 2-D arrays have 1-D arrays as its elements. These can be used to represent matrices.

In [20]:
twoD = np.array([[1, 2, 3], [4, 5, 6]])
# if there's two sets of brackets, then there are two dimensions
twoD

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr.ndim, twoD.ndim

(1, 2)

In [22]:
arr[0], arr[1]

(1, 2)

In [23]:
twoD[0], twoD[0, 0]

(array([1, 2, 3]), 1)

In [24]:
arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr2.ndim

3

In [25]:
arr2, arr2[1], arr2[1, 1], arr2[1, 1, 1]

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([10, 11, 12]),
 11)

In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
# slicing
arr[2:5]

array([3, 4, 5])

In [30]:
arr[1:6:2]

array([2, 4, 6])

In [33]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[1, 1:4:2]

array([7, 9])

In [37]:
arr[0:2, 3]

array([4, 9])

In [38]:
arr[0:2, 1:4:2]

array([[2, 4],
       [7, 9]])

NumPy has different data types.
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [71]:
arr = np.array([1, 2, 3])
arr, arr.dtype

(array([1, 2, 3]), dtype('int32'))

In [70]:
arr = np.array([1, 2, 3], dtype='float')
arr, arr.dtype

(array([1., 2., 3.]), dtype('float64'))

In [74]:
arr2 = arr.astype('int')
arr2, arr.dtype

(array([1, 2, 3]), dtype('int32'))

Copies do not affect original data. Views do affect original data and vice versa.

In [76]:
arr = np.array([1, 2, 3])
arr2 = arr.copy()
arr2[0] = 7
arr, arr2

(array([1, 2, 3]), array([7, 2, 3]))

In [77]:
arr3 = arr2.view()
arr3[1] = 0
arr2, arr3

(array([7, 0, 3]), array([7, 0, 3]))

In [78]:
# if the base attribute of an array is None, then the array is a copy
arr.base, arr2.base, arr3.base

(None, None, array([7, 0, 3]))

In [118]:
arr = np.array([1,2,3])
arr2 = np.array([[1,2,3], [4, 5, 6]])
arr.shape, arr2.shape

((3,), (2, 3))

In [121]:
arr = np.array([1, 2, 3, 4], ndmin=3)
arr.ndim, arr.shape

(3, (1, 1, 4))

In [132]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr2 = arr.reshape(4, 3)
print((arr, arr.shape, arr2, arr2.shape))

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), (12,), array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]]), (4, 3))


In [135]:
arr = np.array([1, 2, 3, 4])
arr2 = arr.reshape(2, 2)
# arr2 is a view
arr2.base

array([1, 2, 3, 4])

In [141]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# NumPy will figure out what the missing dimension needs to be
arr2 = arr.reshape(2, 2, -1)
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [143]:
arr2.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [148]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [151]:
# we have to buffer so numpy has time to change from int to float
for i in np.nditer(arr, flags=['buffered'], op_dtypes='float'):
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0


In [154]:
for i in arr[:, :, 1]:
    print(i)

[2 5]
[ 8 11]
