According to Python, "NumPy is the fundamental package for scientific computing with Python."
It's used for working with arrays. NumPy arrays can be processed faster than Python lists.

In [2]:
# the conventional way to install numpy
import numpy as np
np.__version__

'2.0.1'

In [3]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

Arrays have dimensions. 0-D arrays are just numbers. They're called scalars. 1-D arrays have 0-D arrays as all their elements. 2-D arrays have 1-D arrays as its elements. These can be used to represent matrices.

In [4]:
twoD = np.array([[1, 2, 3], [4, 5, 6]])
# if there's two sets of brackets, then there are two dimensions
twoD

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr.ndim, twoD.ndim

(1, 2)

In [6]:
arr[0], arr[1]

(np.int64(1), np.int64(2))

In [7]:
twoD[0], twoD[0, 0]

(array([1, 2, 3]), np.int64(1))

In [8]:
arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr2.ndim

3

In [9]:
arr2, arr2[1], arr2[1, 1], arr2[1, 1, 1]

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([10, 11, 12]),
 np.int64(11))

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
# slicing
arr[2:5]

array([3, 4, 5])

In [11]:
arr[1:6:2]

array([2, 4, 6])

In [12]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[1, 1:4:2]

array([7, 9])

In [13]:
arr[0:2, 3]

array([4, 9])

In [14]:
arr[0:2, 1:4:2]

array([[2, 4],
       [7, 9]])

NumPy has different data types.
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [15]:
arr = np.array([1, 2, 3])
arr, arr.dtype

(array([1, 2, 3]), dtype('int64'))

In [16]:
arr = np.array([1, 2, 3], dtype='float')
arr, arr.dtype

(array([1., 2., 3.]), dtype('float64'))

In [17]:
arr2 = arr.astype('int')
arr2, arr.dtype

(array([1, 2, 3]), dtype('float64'))

Copies do not affect original data. Views do affect original data and vice versa.

In [18]:
arr = np.array([1, 2, 3])
arr2 = arr.copy()
arr2[0] = 7
arr, arr2

(array([1, 2, 3]), array([7, 2, 3]))

In [19]:
arr3 = arr2.view()
arr3[1] = 0
arr2, arr3

(array([7, 0, 3]), array([7, 0, 3]))

In [20]:
# if the base attribute of an array is None, then the array is a copy
arr.base, arr2.base, arr3.base

(None, None, array([7, 0, 3]))

In [21]:
arr = np.array([1,2,3])
arr2 = np.array([[1,2,3], [4, 5, 6]])
arr.shape, arr2.shape

((3,), (2, 3))

In [22]:
arr = np.array([1, 2, 3, 4], ndmin=3)
arr.ndim, arr.shape

(3, (1, 1, 4))

In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr2 = arr.reshape(4, 3)
print((arr, arr.shape, arr2, arr2.shape))

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]), (12,), array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]]), (4, 3))


In [24]:
arr = np.array([1, 2, 3, 4])
arr2 = arr.reshape(2, 2)
# arr2 is a view
arr2.base

array([1, 2, 3, 4])

In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
# NumPy will figure out what the missing dimension needs to be
arr2 = arr.reshape(2, 2, -1)
arr2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [26]:
arr2.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [27]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [28]:
# we have to buffer so numpy has time to change from int to float
for i in np.nditer(arr, flags=['buffered'], op_dtypes='float'):
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0


In [29]:
for i in arr[:, :, 1]:
    print(i)

[2 5]
[ 8 11]


In [93]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for i, x in np.ndenumerate(arr):
    print(i, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [98]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.concatenate((arr1, arr2))  # arrays are stacked next to each other

array([1, 2, 3, 4, 5, 6])

In [106]:
# stack puts the second array on a new axis
# there are lots of ways to stack
np.stack((arr1, arr2))

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
# by default axis=0
# axis 1 means the inputs are stacked column-wise --> same as dstack
# axis 0 means the inputs are stacked row-wise --> same as vstack
np.stack((arr1, arr2), 1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [113]:
np.hstack((arr1, arr2))  # arrays are stacked next to each other horizontally

array([1, 2, 3, 4, 5, 6])

In [114]:
np.vstack((arr1, arr2))  # arrays are stacked on top of each other vertically

array([[1, 2, 3],
       [4, 5, 6]])

In [119]:
np.dstack((arr1, arr2))  # arrays are stacked next to each other

array([[[1, 4],
        [2, 5],
        [3, 6]]])