According to Python, "NumPy is the fundamental package for scientific computing with Python."
It's used for working with arrays. NumPy arrays can be processed faster than Python lists.

In [37]:
# the conventional way to install numpy
numpy: import numpy as np
np.__version__

SyntaxError: invalid syntax (1724952845.py, line 2)

In [42]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

Arrays have dimensions. 0-D arrays are just numbers. They're called scalars. 1-D arrays have 0-D arrays as all their elements. 2-D arrays have 1-D arrays as its elements. These can be used to represent matrices.

In [43]:
twoD = np.array([[1, 2, 3], [4, 5, 6]])
# if there's two sets of brackets, then there are two dimensions
twoD

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr.ndim, twoD.ndim

(1, 2)

In [63]:
arr[0], arr[1]

(np.int64(1), np.int64(2))

In [68]:
twoD[0], twoD[0, 0]

(array([1, 2, 3]), np.int64(1))

In [67]:
arr2 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr2.ndim

3

In [75]:
arr2[1], arr2[1, 1], arr2[1, 1, 1]

(array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([10, 11, 12]),
 np.int64(11))